Blog app - integration specs for views and fix n+1 problems
Movgto/my-blog-app pull request #8
Opened 2023-11-15 23:40 UTC by Movgto

- Made sure that the N+1 problem is solved when fetching all posts and their comments for a user.
- Used Capybara to write integration tests for each view in the project.

2023-11-16 16:10 UTC, codepantha requested changes
# STATUS: REQUIRES CHANGES ♻️ 

## Hi team 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media1.giphy.com/media/xUOxfh6ZM75efM3Bqo/giphy-downsized-medium.gif"/>

## Highlights 🎯 
✔️ Descriptive PR
✔️ Good commit history
✔️ No linter errors 🟢 

## Required Changes ♻️
_Check the comments under the review._

- [ ] Please fix n+1 problems and include the before and after screenshots of your app's logs in your PR description 👍 

![image](https://github.com/Movgto/my-blog-app/assets/46839548/f21ecf39-3283-4fbf-876c-6c5886fb37fc)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- n/a

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-16 16:10 UTC, codepantha commented on spec/system/users_views_spec.rb
> +  end
- [ ] The test requires that you should assert that the user is redirected to the "user show page" not the "user post index page" as you have done here. Please ensure that there is a redirect to the appropriate page 👍

2023-11-16 16:10 UTC, codepantha commented on spec/system/users_views_spec.rb
> +    let(:comment3) { Comment.new(user:, post: post3, text: 'Comment 3') }
- [ ] According to requirements, you should have separate spec files for both `User index page` and `User show page`. Please ensure that the tests covering these separate pages are in their separate files 👍

2023-11-16 16:10 UTC, codepantha commented on spec/system/users_views_spec.rb
> +  end
- [ ] Please add a test that redirects to the post's show page when you click on a user's post 👍 
![image](https://github.com/Movgto/my-blog-app/assets/46839548/4ab6cfce-421d-47dc-a9b7-086bb5ce1839)

2023-11-16 16:10 UTC, codepantha commented on spec/system/posts_views_spec.rb
> +    end
- [ ] The test description here does not match with the assertion. I think you meant `it 'can see who wrote the post' do`

2023-11-16 16:10 UTC, codepantha commented on spec/system/posts_views_spec.rb
> +    end
- [ ] I think you meant to assert that "you can see the post body" here. Please change the description of this test 👍

2023-11-17 14:59 UTC, DeliceLydia approved these changes
## Hi @Movgto, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
# Congratulations! 🎉 

## Highlights
- Addressed changes requested



### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-18 02:03 UTC, merged